### ISSUE TITLE
OPMI will donate clinical trial specific terms to CTO

### ISSUE THREAD

**Issue by linikujp** [ClinicalTrialOntology/CTO#10]
1. Clinical trial 
2. clinical trial registry and clinical trial repostiory as synonym

**Comment by linikujp** [comment]
3. human subject study (currently http://purl.obolibrary.org/obo/OPMI_0000418)
@yongqunh -- please decide if you'd like to give this term to CTO.

**Comment by linikujp** [comment]
4. clinical trial start date (http://purl.obolibrary.org/obo/OPMI_0000295)
5. clinical trial primary completion date (http://purl.obolibrary.org/obo/OPMI_0000299)
6. clinical trial study completion date (http://purl.obolibrary.org/obo/OPMI_0000298)

**Comment by linikujp** [comment]
7. title of clinical trial (http://purl.obolibrary.org/obo/OPMI_0000290)-- ICO has a clinical trial title (http://purl.obolibrary.org/obo/ICO_0000066).
8. lay title of clinical trial (http://purl.obolibrary.org/obo/OPMI_0000292)
9. official title of clinical trial (http://purl.obolibrary.org/obo/OPMI_0000291)

**Comment by linikujp** [comment]
10. a bunch of clinical trial registry identifiers.
![image](https://user-images.githubusercontent.com/8712765/82136597-88635800-97dd-11ea-83c7-375a15287900.png)

**Comment by yongqunh** [comment]
Looks good to me. I will later process and work with you to donate these terms from OPMI to CTO.

**Comment by yongqunh** [comment]
I generated a related tracker in OPMI: 
https://github.com/OPMI/opmi/issues/5 
in order to summarize the process and to receive any possible feedback.

**Comment by linikujp** [comment]
11. a bunch of contact, sponsor terms and related roles, including contact information, especially clinical trial specific ones need to move from OPMI to CTO.

**Comment by johannes-darms** [comment]
Done in #26. Summary of migrated ID below:

| old OPMI ID  | new CTO ID  |
| ------------- | ------------- |
|http://purl.obolibrary.org/obo/OPMI_0000300|http://purl.obolibrary.org/obo/CTO_0000200|
|http://purl.obolibrary.org/obo/OPMI_0000367|http://purl.obolibrary.org/obo/CTO_0000201|                                                                                     
  |http://purl.obolibrary.org/obo/OPMI_0000368|http://purl.obolibrary.org/obo/CTO_0000203|
  |http://purl.obolibrary.org/obo/OPMI_0000369|http://purl.obolibrary.org/obo/CTO_0000204|
  |http://purl.obolibrary.org/obo/OPMI_0000370|http://purl.obolibrary.org/obo/CTO_0000205|
  |http://purl.obolibrary.org/obo/OPMI_0000371|http://purl.obolibrary.org/obo/CTO_0000206|
  |http://purl.obolibrary.org/obo/OPMI_0000372|http://purl.obolibrary.org/obo/CTO_0000202|
  |http://purl.obolibrary.org/obo/OPMI_0000300|http://purl.obolibrary.org/obo/CTO_0000200|
   |http://purl.obolibrary.org/obo/OPMI_0004508|http://purl.obolibrary.org/obo/CTO_0000207|
  |http://purl.obolibrary.org/obo/OPMI_0000360|http://purl.obolibrary.org/obo/CTO_0000208|
   |http://purl.obolibrary.org/obo/OPMI_0000356|http://purl.obolibrary.org/obo/CTO_0000209|
   |http://purl.obolibrary.org/obo/OPMI_0000358|http://purl.obolibrary.org/obo/CTO_0000210|
   |http://purl.obolibrary.org/obo/OPMI_0000359|http://purl.obolibrary.org/obo/CTO_0000211|
  |http://purl.obolibrary.org/obo/OPMI_0000357|http://purl.obolibrary.org/obo/CTO_0000212|                                                                                                            
  |http://purl.obolibrary.org/obo/OPMI_0000289|http://purl.obolibrary.org/obo/CTO_0000213|                                                                                                            
   |http://purl.obolibrary.org/obo/OPMI_0000295|http://purl.obolibrary.org/obo/CTO_0000214|                                                                                                            
   |http://purl.obolibrary.org/obo/OPMI_0000299|http://purl.obolibrary.org/obo/CTO_0000215|                                                                                                            
 |http://purl.obolibrary.org/obo/OPMI_0000298|http://purl.obolibrary.org/obo/CTO_0000216|                                                                                                            
  |http://purl.obolibrary.org/obo/OPMI_0000290|http://purl.obolibrary.org/obo/CTO_0000217|                                                                                                            
 |http://purl.obolibrary.org/obo/OPMI_0000292|http://purl.obolibrary.org/obo/CTO_0000218|                                                                                                            
 |http://purl.obolibrary.org/obo/OPMI_0000291|http://purl.obolibrary.org/obo/CTO_0000219|                                                                                                            
 |http://purl.obolibrary.org/obo/OPMI_0004507|http://purl.obolibrary.org/obo/CTO_0000220|
