### ISSUE TITLE
IRI format issue

### ISSUE THREAD

**Issue by linikujp** [ClinicalTrialOntology/CTO#12]
Current CTO IRI is formatted as https://bio.scai.fraunhofer.de/ontology/CTO#[term]
According to OBO Foundry principle, the ontology IRI format should be formulated as this:

> The OBI class ‘imaging assay’ has the following URI: http://purl.obolibrary.org/obo/OBI_0000185

Please see : http://www.obofoundry.org/principles/fp-003-uris.html

**Comment by sgebel** [comment]
we will take care on that

**Comment by linikujp** [comment]
After @sgebel changed the CTO IRI, we (@yongqunh and @linikujp ) will be able to work on the OPMI file for ontology engineering.

**Comment by linikujp** [comment]
The IRI is still wrong:
Instead of "https://bio.scai.fraunhofer.de/ontology/CTO#000001", it should be "https://bio.scai.fraunhofer.de/ontology/**CTO_000001**"

**Comment by linikujp** [comment]
Another question is:
Did you resolve the URL for IRI? For instance, if we click the IRI, it should take us to the page showing this term....

**Comment by johannes-darms** [comment]
> The IRI is still wrong:
> Instead of "https://bio.scai.fraunhofer.de/ontology/CTO#000001", it should be "https://bio.scai.fraunhofer.de/ontology/CTO_000001"
Sorry my bad, I'll change them ASAP. 
> And maybe make the digit to 7 instead of 6 here.
Sure!

**Comment by johannes-darms** [comment]
> Another question is:
> Did you resolve the URL for IRI? For instance, if we click the IRI, it should take us to the page showing this term.... Oliver's ontobee and Leon's PubChem RDF page are the examples.

Currently they are not resolved. We can utilize an OLS hosted on our side to do so. We only need add an URL rewrite.

**Comment by johannes-darms** [comment]
#15 solves it.

**Comment by linikujp** [comment]
Not yet.
I see the ID shows bio.scai.fraunhofer.de/ontology/**CTO#CTO_0000016**
It should be **CTO_0000016** The CTO# needs to be deleted.

**Comment by johannes-darms** [comment]
> The URI should be constructed from a base URI, a prefix that is unique within the Foundry (e.g. GO, CHEBI, CL) and a local identifier (e.g. 0000001). The local identifier should not consist of labels or mnemonics meaningful to humans [Principle: URI/Identifier Space (principle 3) ](http://www.obofoundry.org/principles/fp-003-uris.html)

I changed the  base URI is `bio.scai.fraunhofer.de/ontology/CTO_` and the local identifier 7 digits e.g. `0000016`.

**Comment by yongqunh** [comment]
Are we targeting to make CTO an OBO ontology? In this case, we may consider using the standard: 
http://purl.obolibrary.org/obo/CTO_xxxxxxx

**Comment by yongqunh** [comment]
I also think we should soon submit a namespace request to OBO foundry to have CTO be included as an OBO ontology. We would rather do it sooner than later in case some other group takes a lead to apply.

**Comment by linikujp** [comment]
Per meeting on May 22, 2020, the group agreed to change the IRI to OBO formal : 

> Are we targeting to make CTO an OBO ontology? In this case, we may consider using the standard:
> http://purl.obolibrary.org/obo/CTO_xxxxxxx

**Comment by johannes-darms** [comment]
The current schema is `bio.scai.fraunhofer.de/ontology/` and the identifier are matching this regex `CTO_\d{7}`. We  applied for a OBO purl address (https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1220). Once that is accepted I'll update the base URI.
